name: deadline_manager
description: Web application for managing deadlines.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.4
  categories_repository:
    path: packages/categories_repository
  deadlines_repository:
    path: packages/deadlines_repository
  equatable: ^2.0.5
  firebase_core: ^3.1.0
  firebase_ui_auth: ^1.15.0
  firestore_categories_api:
    path: packages/firestore_categories_api
  firestore_deadlines_api:
    path: packages/firestore_deadlines_api
  firestore_permissions_api:
    path: packages/firestore_permissions_api
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.1.4
  intl: ^0.19.0
  permissions_repository:
    path: packages/permissions_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
