name: firestore_deadlines_api
description: An implementation of the DeadlinesApi that uses Cloud Firestore.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  deadlines_api:
    path: ../deadlines_api
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
