name: firestore_deadlines_api
description: An implementation of the DeadlinesApi that uses Cloud Firestore.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  deadlines_api:
    path: ../deadlines_api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
