name: authentication_repository
description: A repository that handles authentication related requests.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^5.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
