name: firestore_categories_api
description: An implementation of the CategoriesApi that uses Cloud Firestore.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  categories_api:
    path: ../categories_api
  cloud_firestore: ^5.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
