name: app_ui
description: A package with the common widgets and helper classes of the app.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  deadlines_api:
    path: ../deadlines_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
