name: categories_api
description: The interface and models for providing access to categories.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
