name: authentication_repository

on:
  pull_request:
    paths:
      - "packages/authentication_repository/**"
      - ".github/workflows/authentication_repository.yaml"
    branches: [master]
  push:
    branches: [master]

jobs:
  flutter_tests:
    defaults:
      run:
        working-directory: packages/authentication_repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze package source
        run: flutter analyze lib

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
