name: firestore_permissions_api
description: An implementation of the PermissionsApi that uses Cloud Firestore.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  flutter:
    sdk: flutter
  permissions_api:
    path: ../permissions_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_cloud_firestore: ^3.0.2
